name: diet
description: DietFriends Core Libraries for Dart
version: 1.0.0
homepage: https://github.com/dietfriends/diet

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  quiver: ^3.0.1
  async: ^2.7.0
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.4

